server:
  port: 8085

spring:
  application:
    name: bucket-service
  datasource:
    url: jdbc:postgresql://localhost:5432/s3system
    driverClassName: org.postgresql.Driver
    username: s3user
    password: s3password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cache:
    type: concurrentMap

logging:
  level:
    root: INFO
    com.s3.common.security: DEBUG
    com.s3.common.config: DEBUG
    com.s3: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

auth:
  jwt:
    # A 256-bit key (Base64-encoded)
    secret: "b4J2zwtv5TIis+vW0hkNpnKUq9frHNF+IGpEZ4a6t+M="
    expiration-ms: 86400000
s3:
  events:
    enabled: false