server:
  port: 8088

spring:
  application:
    name: metadata-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: metadata-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: latest
      properties:
        spring.json.trusted.packages: "*"
    listener:
      missing-topics-fatal: false

  datasource:
    url: jdbc:postgresql://localhost:5432/s3system
    username: s3user
    password: s3password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate   # update only in dev
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    root: INFO
    com.s3: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

auth:
  jwt:
    secret: "b4J2zwtv5TIis+vW0hkNpnKUq9frHNF+IGpEZ4a6t+M="
    expiration-ms: 86400000

s3:
  events:
    service-name: metadata-service
    topics:
      object: s3.object.events
      metadata: s3.metadata.events
      bucket: s3.bucket.events
