server:
  port: 8086

spring:
  application:
    name: object-service
  datasource:
    url: jdbc:postgresql://localhost:5432/s3system
    username: s3user
    password: s3password
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
  jpa:
    hibernate:
      ddl-auto: update   # use 'validate' in prod
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB        # maximum size of a single file
      max-request-size: 120MB     # maximum size of entire request (all files + form data)
#  config:
#    import: optional:classpath:application-common.yml
  # Enable caching (can later switch to Redis)
#  cache:
#    type: caffeine   # or simple, or redis

logging:
  level:
    root: INFO
    com.s3: INFO

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
      path: /swagger-ui.html
# File storage location for object binaries
storage:
  location: ./data/s3/objects

bucket:
  service:
    url: http://localhost:8085

# JWT settings (you can override with environment variables)
auth:
  jwt:
    secret: "b4J2zwtv5TIis+vW0hkNpnKUq9frHNF+IGpEZ4a6t+M="
    expiration-ms: 86400000

s3:
  events:
    enabled: true
    service-name: ${spring.application.name}
    topics:
      object: s3.object.events
      metadata: s3.metadata.events