spring:
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      spring.json.trusted.packages: "*"

logging:
  level:
    root: INFO

auth:
  jwt:
    secret: "b4J2zwtv5TIis+vW0hkNpnKUq9frHNF+IGpEZ4a6t+M="
    expiration-ms: 86400000

s3:
  events:
    topics:
      object: s3.object.events
      metadata: s3.metadata.events
